on:
  push:
    tags:
      - "*.*.*"

jobs:
  build_wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: SetUpPython
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Buildwheel
        run: |
          python -m pip install --user --upgrade build
          python -m build .
          echo "VERSION = $(python setup.py --version)" >> $GITHUB_OUTPUT
      - name: Release
        uses: "softprops/action-gh-release@v1"
        with:
          files: |
            ./dist/*.whl

